version: '3.3'
services:
  proxy:
    image: traefik
    command:
      - --api 
      - --api.dashboard=true 
      - --api.statistics
      - --docker 
      - --docker.domain=libaibuaidufu.live
      - --docker.watch 
      - --docker.swarmmode=true 
      - --logLevel=INFO
    deploy:
      labels:
        - traefik.backend=traefik
        - traefik.frontend.rule=Host:monitor.libaibuaidufu.live
        - traefik.port=8080
        - traefik.docker.network=traefik_proxy
    networks:
      - proxy
    ports:
      - "80:80"
      - "8000:8080"
      #- "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
networks:
  proxy:
