version: "3.3"
services:
  server:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
    networks:
      - traefik_proxy
    deploy:
      labels:
        - traefik.backend=jaeger
        - traefik.frontend.rule=Host:jaeger.cloud-labs.io
        - traefik.docker.network=traefik_proxy
        - traefik.port=16686
networks:
  traefik_proxy:
    external: true