version: '3'
services:
  server:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    networks:
      - proxy
    labels:
      - traefik.backend=portainer
      - traefik.frontend.rule=Host:console.cloud.ronggle.com
      - traefik.docker.network=proxy
      - traefik.port=9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  proxy:
    external: true
